# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OkpIxO3os1Mw6gZhBiahOhIy7oKJG32v
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
fake_news_path = 'fake.csv'
fake_news = pd.read_csv(fake_news_path)
fake_news["type"] = "fake"
true_news_path = 'true.csv'
true_news = pd.read_csv(true_news_path)
true_news["type"] = "true"
news = pd.concat([fake_news, true_news], ignore_index=True)
news['content'] = news['title'] + ' ' + news['text'] + ' ' + news['subject']
X_train, X_test, y_train, y_test = train_test_split(news['content'], news['type'], test_size=0.3, random_state=42)
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)
y_pred = model.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, y_pred))